### ISSUE TITLE
FidRadDB download folders

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#119]
When activating FidRadDB download, it is designed to use the data file acquisition time to name a subfolder in which to store the characterization files. This means that every file processed will redundantly download and copy the same files into /Data; as many as hundreds of times per cruise.

Clearly, the files downloaded will need to depend on the data acquisition time, but once matched to the proper FidRadDB files, the directory they are stored in should be named after the characterization file "era" rather than the data file datetime. The era would be some period in which the all the matched characterizations were completed, which can differ by weeks or more between instruments. 

FidRadDB_api should match DB files to field data files, identify the DB group era, and check if those files have already been downloaded locally. E.g., HyperCP/Data/FidRadDB_characterization/TriOS/UT_2022_A/ for DB files generated by UT between April and July of 2022 for that instrument suite. If another characterization is done for the suite, it could be "UT_2022_B", or some similar system.

**Comment by juanchossn** [comment]
Juan will try to fix this while Alexis is on leave.

**Comment by juanchossn** [comment]
Issue is now solved (PR very soon). Whenever a file is missing, FidRadDB will skip the search. This is typically the case for ANGULAR in the case of L_x sensors and POLAR for Es sensor:

Sensor 0488: POLAR file not found. Skipping FidRadBD search...
Sensor 0385: ANGULAR file not found. Skipping FidRadBD search...
Sensor 0386: ANGULAR file not found. Skipping FidRadBD search...

Exceptions due to non-existing cal/char files now handled directly in FidradDB_api function
If a missing cal/char file entails an error, this should be handled while performing the particular correction... to be checked

**Comment by oceancolorcoder** [comment]
Resolved with 1ea458e
