### ISSUE TITLE
Failed 6S at L1B needs catch resolution

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#203]
When py6S fails it returns all NaNs resulting in all NaNs in the Es after cosine correction.

When this happens, processing should fail rather than yield a L1B file. 

Eventually, when this happens (if it happens with the py6_json implementation) a preferable solution would be to fall back to a simpler RT model such as Gregg and Carter, L&O, 1990.

**Comment by raphidoc** [comment]
I'm currently testing on this. Only two wavelengths have 0 (`direct` and `diffuse`) values and NaN (`irr_*`) at 6S output. I'm implementing the same solution for NaN as already written when `direct` has a value of 0.

**Comment by oceancolorcoder** [comment]
Great! Please send a PR to nasa:dev when complete. This should make G&C90 fallback unnecessary, right?

**Comment by raphidoc** [comment]
This didn't fix the problem. The NaN are **created** by https://github.com/nasa/HyperCP/blob/18815ce8334f649336f6a633a86b2684426c204b/Source/ProcessL1b_FRMCal.py#L136-L152

The problem seems to come from the fact that there is only one bin (`n_bin = 1`), so the 6S model is run just once, and we cannot interpolate with just one x step (i.e. if `len(x_bin) == 1`). Instead of returning an error, `interp1d` returns an array of the requested shape full of `NaN` (a strange choice, in my opinion).

Inspecting the six values of `datetime`, it seems that there are only 25 seconds of data, consequently `n_min = 43` `n_bin = 0` and is then incremented by 1.  https://github.com/nasa/HyperCP/blob/18815ce8334f649336f6a633a86b2684426c204b/Source/ProcessL1b_FRMCal.py#L80-L86

I'm unsure about the logic of the 6S computation over the bin or ensemble (what is the difference ?). If the problem comes from the fact that there is only one bin to compute on, we could run 6S for the beginning and the end of this bin and interpolate between those values.

**Comment by oceancolorcoder** [comment]
For efficiency, we elected to only calculate 6S once every three minutes of data at L1B and then interpolate it to the timestamps of the radiometry rather than running it for every timestamp. That is the "bin" in L1B for 6S. 

Ensembles only come later, in L2, when we bin all data to (typically) 5 minutes (adjustable in the configuration).

Alexis recently implemented the L1B 3 min binning and I have invited him to respond here.

**Comment by AlexisDeru** [comment]
hi, thank you for catching that, I will check the interpolation issue.
we should have at least 2 bins each time but may be there is some shorter cast

**Comment by raphidoc** [comment]
@oceancolorcoder Yes, I think the G&C model is unnecessary as the problem doesn't come from 6S. Still, I believe we need to discuss how to deal with `NaN` returned by 6S at some wavelength (this issue: #205 )

@ARamsay17 For reference if needed, here is the G&C implementation in R written by my colleague @homas01123: https://github.com/homas01123/SABER/blob/master/R/gregg_carder_ed.R

**Comment by AlexisDeru** [comment]
Hi, I guess there is 2 different issues here, which might explain the confusion.

The Trios test case (2022-07-14_09-35-15_000_SAM_8268_L1B.hdf) have a very small duration, only 25 sec. This explain why we have only 1 bin and why the py6s interpolation fail. What should do the HCP in these cases ? Reject the product or process anyway ?

For the NASA test case (FRM4SOC2_FICE22_NASA_20220719_100000_L1BQC.hdf). I am not able to reproduce the issue. This file run up to L2 on my side without NaN, while the one Dirk put on the box is full of NaN (at L1BQC level). so I am not sure to understand what is happening here ?

**Comment by raphidoc** [comment]
I was also able to process the file FRM4SOC2_FICE22_NASA_20220719_100000_L1A.hdf to L2. 
The only `NaN` values inside are at 443.05, 633.45, and 670.13 nm.

**Comment by oceancolorcoder** [comment]
I can confirm that my current dev branch is able to produce that L1BQC file without the NaNs and runs up to L2.

Keeping the short L1B with only 1 6S result sounds fine. True, such a short file should not survive L2.

I believe that resolves this issue, and we can shift discussing of the NaNs returned by 6S to #205
