### ISSUE TITLE
Add BRDF uncertainties

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#85]
Based on today's discussion, these uncertainties are known, but have not been rolled in. Hopefully we can incorporate these also by next week for the merge to master.

@ARamsay17

**Comment by juanchossn** [comment]
Tamito Kamiyama (Aequora, BRDF4OLCI team) looking into it.

**Comment by juanchossn** [comment]
Suggest change in name of ticket: "Add BRDF uncertainties"


-	BRDF model uncertainties (the +0 term): Implemented by Marco Talone. NB: We don’t need to run all the methods to calculate model error as in the case of skyglint. This is because Marco Talone generated a simplified LUT (contracting the IOP dependence, proved negligible when compared to geometry dependence) containing the std of the difference between the models. See ```brdf_uncertainty``` in [this](https://github.com/nasa/HyperCP/blob/dev/Source/ocbrdf/main.py) script. We should follow a similar approach for skyglint to avoid the need of running both of the approaches everytime.
-	BRDF “sensitivity to inputs” uncertainties: to be implemented by NPL with punpy.

**Comment by oceancolorcoder** [comment]
Closed with 6f82ab3.
